cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${NODE_NAME}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}

bootstrap:
  memory_lock: ${MEMORY_LOCK}

searchguard:
  ssl:
    transport:
      keystore_filepath: certs/node-keystore.jks
      keystore_password: changeit
      truststore_filepath: certs/truststore.jks
      truststore_password: changeit
      enforce_hostname_verification: false
      enabled: ${SEARCHGUARD_SSL_TRANSPORT_ENABLED}
    http:
      enabled: ${SEARCHGUARD_SSL_HTTP_ENABLED}
      keystore_filepath: certs/node-keystore.jks
      keystore_password: changeit
      truststore_filepath: certs/truststore.jks
      truststore_password: changeit

metrics:
  statsd:
    host: ${STATSD_HOST}

indices.memory.index_buffer_size: 15%
indices.breaker.total.limit: 30%
indices.breaker.request.limit: 6%
indices.breaker.fielddata.limit: 3%
indices.queries.cache.count: 500
indices.queries.cache.size: 5%
thread_pool.bulk.queue_size: 1024
